### ISSUE TITLE
Got CachePartialUpdateException while running IgnitePutGetBenchmark

### ISSUE THREAD

**Issue by rdiyewar** [apacheignite/yardstick-ignite#2]
I am running IgnitePutGetBenchmark benchmark in client-server mode and driver failed with following exception

```
ERROR: Shutting down benchmark driver to unexpected exception.
Type '--help' for usage.
org.apache.ignite.cache.CachePartialUpdateException: Failed to update keys (retry update if possible).: [144321]
        at org.apache.ignite.internal.processors.cache.GridCacheUtils.convertToCacheException(GridCacheUtils.java:1805)
        at org.apache.ignite.internal.processors.cache.IgniteCacheProxy.cacheException(IgniteCacheProxy.java:1450)
        at org.apache.ignite.internal.processors.cache.IgniteCacheProxy.put(IgniteCacheProxy.java:762)
        at org.apache.ignite.yardstick.cache.IgnitePutBenchmark.test(IgnitePutBenchmark.java:32)
        at org.yardstickframework.impl.BenchmarkRunner$2.run(BenchmarkRunner.java:165)
        at java.lang.Thread.run(Thread.java:745)
Caused by: class org.apache.ignite.internal.processors.cache.CachePartialUpdateCheckedException: Failed to update keys (retry update if possible).: [144321]
        at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridNearAtomicUpdateFuture.addFailedKeys(GridNearAtomicUpdateFuture.java:893)
        at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridNearAtomicUpdateFuture.onResult(GridNearAtomicUpdateFuture.java:351)
        at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache.processNearAtomicUpdateResponse(GridDhtAtomicCache.java:2458)
        at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache.access$700(GridDhtAtomicCache.java:68)
        at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache$6.apply(GridDhtAtomicCache.java:201)
        at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache$6.apply(GridDhtAtomicCache.java:199)
        at org.apache.ignite.internal.processors.cache.GridCacheIoManager.processMessage(GridCacheIoManager.java:299)
        at org.apache.ignite.internal.processors.cache.GridCacheIoManager.onMessage0(GridCacheIoManager.java:212)
        at org.apache.ignite.internal.processors.cache.GridCacheIoManager.access$300(GridCacheIoManager.java:44)
        at org.apache.ignite.internal.processors.cache.GridCacheIoManager$1.onMessage(GridCacheIoManager.java:132)
        at org.apache.ignite.internal.managers.communication.GridIoManager.processRegularMessage0(GridIoManager.java:664)
        at org.apache.ignite.internal.managers.communication.GridIoManager.access$1500(GridIoManager.java:57)
        at org.apache.ignite.internal.managers.communication.GridIoManager$5.run(GridIoManager.java:627)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        ... 1 more
        Suppressed: class org.apache.ignite.IgniteCheckedException: Failed to update keys on primary node.
                at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridNearAtomicUpdateResponse.addFailedKeys(GridNearAtomicUpdateResponse.java:344)
                at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache.updateAllAsyncInternal0(GridDhtAtomicCache.java:1098)
                at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache.updateAllAsyncInternal(GridDhtAtomicCache.java:1049)
                at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache.processNearAtomicUpdateRequest(GridDhtAtomicCache.java:2441)
                at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache.access$600(GridDhtAtomicCache.java:68)
                at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache$5.apply(GridDhtAtomicCache.java:195)
                at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache$5.apply(GridDhtAtomicCache.java:193)
                ... 10 more
                Suppressed: class org.apache.ignite.IgniteCheckedException: Failed to perform cache operation (cache is stopped): atomic
                        ... 16 more
```

Sometime driver fails with following exception:

```
org.apache.ignite.cache.CacheAtomicUpdateTimeoutException: Cache update timeout out (consider increasing networkTimeout configuration property).
        at org.apache.ignite.internal.processors.cache.GridCacheUtils.convertToCacheException(GridCacheUtils.java:1807)
        at org.apache.ignite.internal.processors.cache.IgniteCacheProxy.cacheException(IgniteCacheProxy.java:1450)
        at org.apache.ignite.internal.processors.cache.IgniteCacheProxy.put(IgniteCacheProxy.java:762)
        at org.apache.ignite.yardstick.cache.IgnitePutGetBenchmark.test(IgnitePutGetBenchmark.java:37)
        at org.yardstickframework.impl.BenchmarkRunner$2.run(BenchmarkRunner.java:165)
        at java.lang.Thread.run(Thread.java:745)
Caused by: class org.apache.ignite.internal.processors.cache.CacheAtomicUpdateTimeoutCheckedException: Cache update timeout out (consider increasing networkTimeout configuration property).
        at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridNearAtomicUpdateFuture.checkTimeout(GridNearAtomicUpdateFuture.java:279)
        at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache$22.onTimeout(GridDhtAtomicCache.java:2267)
        at org.apache.ignite.internal.processors.timeout.GridTimeoutProcessor$TimeoutWorker.body(GridTimeoutProcessor.java:133)
        at org.apache.ignite.internal.util.worker.GridWorker.run(GridWorker.java:107)
        ... 1 more
```

There are no expections in servers. What could be the problem here and how to resolve it.

Thanks!

**Comment by ashutakGG** [comment]
Try to increase network timeouts.

Add these properties on all nodes to `TcpDiscoverySpi` to increase timeouts:

`<property name="networkTimeout" value="5000"/>`
`<property name="socketTimeout" value="5000"/>`
`<property name="ackTimeout" value="5000"/>`
`<property name="heartbeatFrequency" value="2000"/>`

It should help.

Thanks,
Artem.

**Comment by rdiyewar** [comment]
Still getting this `CachePartialUpdateException` even after setting timeout values, how to verify that they are correctly applied. 

I should have mentioned this earlier that the exception is coming after setting `<property name="atomicWriteOrderMode" value="PRIMARY"/>` and only for IgnitePutGetBenchmark. 

Thanks,
Rahul

**Comment by ntikhonov** [comment]
Can you provide full logs from client and servers? 
I've updated ignite version to latest. Could you try it?

**Comment by rdiyewar** [comment]
Running with latest ignite solved the issue. thanks!
